# Generated by Django 5.0.4 on 2026-04-11 15:20

from django.db import migrations

from apps.core import models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='students/', blank=True, null=True),
        ),
    ]
