# Generated by Django 5.0.4 on 2026-04-11 17:18

from django.db import migrations, models





class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='students/', blank=True, null=True),
        ),
    ]
