# Generated by Django 5.0.4 on 2026-04-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_alter_student_current_academic_level_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
